### ISSUE TITLE
Are there any specific requirement on the versions?

### ISSUE THREAD

**Issue by marghidanu** [opener-project/ner#1]
I'm trying to use the ner package but it keeps failing on my Ubuntu 12.04 environment. I've used different versions of JRuby and Nokogiri but the application still fails with the following error:

```
xa/kaflib/Entity.java:132:in `getSpanStr': java.lang.NullPointerException
    from ixa/kaflib/ReadWriteManager.java:1073:in `KAFToDOM'
    from ixa/kaflib/ReadWriteManager.java:77:in `kafToStr'
    from ixa/kaflib/KAFDocument.java:949:in `toString'
    from java/lang/reflect/Method.java:606:in `invoke'
    from /usr/share/ruby-rvm/gems/jruby-1.7.18/gems/opener-ner-base-3.0.1/lib/opener/ners/base.rb:94:in `run'
    from /usr/share/ruby-rvm/gems/jruby-1.7.18/gems/opener-ner-3.0.0/lib/opener/ner.rb:65:in `run'
    from /usr/share/ruby-rvm/gems/jruby-1.7.18/gems/opener-ner-3.0.0/lib/opener/ner/cli.rb:58:in `configure_slop'
    from org/jruby/RubyProc.java:271:in `call'
    from /usr/share/ruby-rvm/gems/jruby-1.7.18/gems/slop-3.6.0/lib/slop.rb:260:in `parse!'
    from /usr/share/ruby-rvm/gems/jruby-1.7.18/gems/slop-3.6.0/lib/slop.rb:211:in `parse'
    from /usr/share/ruby-rvm/gems/jruby-1.7.18/gems/opener-ner-3.0.0/lib/opener/ner/cli.rb:20:in `run'
    from /usr/share/ruby-rvm/gems/jruby-1.7.18/gems/opener-ner-3.0.0/bin/ner:7:in `(root)'
    from org/jruby/RubyKernel.java:1087:in `load'
    from /usr/share/ruby-rvm/gems/jruby-1.7.18/bin/ner:23:in `(root)'
    from usr/share/ruby_minus_rvm/gems/jruby_minus_1_dot_7_dot_18/bin//usr/share/ruby-rvm/gems/jruby-1.7.18/bin/ner:23:in `(root)'
```

Are there any requirements for specific versions other than the ones listed on the installation guide? The command that failed with this error was:

```
echo "find flights from San Francisco to NYC" | language-identifier | tokenizer | ner
```

**Comment by giannismelidis** [comment]
Hi there! Thanks for using OpeNER.

No there are no extra requirements other than these mentioned. Ner needs also the pos-tagger component in order to run. So using this command should work for you:

```
echo "find flights from San Francisco to NYC" | language-identifier | tokenizer | pos-tagger | ner
```

**Comment by marghidanu** [comment]
@giannismelidis thank you very much! Very cool project you've got there! Thanks for your answer!
